//------------------------------------------------------------------------------
// <auto-generated>
//    Ten kod źródłowy został wygenerowany na podstawie szablonu.
//
//    Ręczne modyfikacje tego pliku mogą spowodować nieoczekiwane zachowanie aplikacji.
//    Ręczne modyfikacje tego pliku zostaną zastąpione w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp17
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.products = new HashSet<product>();
        }
    
        public int category_id { get; set; }
        public string category_name { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
